# Generated by Django 5.0.3 on 2024-05-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateRangeRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('startDate', models.JSONField()),
                ('endDate', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarEventModel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('startDateTime', models.JSONField()),
                ('endDateTime', models.JSONField()),
            ],
        ),
    ]
