# Generated by Django 5.0.3 on 2024-05-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0002_alter_daterangerequestmodel_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterangerequestmodel',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daterangerequestmodel',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
