# Generated by Django 5.0.3 on 2024-05-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0003_alter_daterangerequestmodel_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendareventmodel',
            name='endDateTime',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='googlecalendareventmodel',
            name='startDateTime',
            field=models.JSONField(),
        ),
    ]
